- name: restart systemd-resolved
  service:
    name: systemd-resolved
    state: restarted

- name: restart systemd-networkd
  service:
    name: systemd-networkd
    state: restarted

- name: restart teamd
  service:
    name: 'teamd-{{ network_team.name }}.service'
    state: restarted

- name: reload systemd
  systemd:
    daemon_reload: yes

- name: update initramfs
  command:
    cmd: /usr/sbin/update-initramfs -u -k all
